generate-links: chmod the file first because stat()'ing
Should fix,

```
Error: ENOENT: no such file or directory, stat 'D:\a\esy-bash\esy-bash\.cygwin\bin\apropos'
    at Object.statSync (node:fs:1615:3)
    at Object.statSync (D:\a\esy-bash\esy-bash\node_modules\graceful-fs\polyfills.js:308:16)
    at getAllHardLinks (D:\a\esy-bash\esy-bash\scripts\generate-links.js:91:22)
```

Likely arose after the github actions caching/restore .cygwin folder